Repository upb-uc4/lagom-core, pull requests merged in 2020-11, with the labels that each got.

#358 Feature/etags
  product_code/authentication_service/CHANGELOG.md
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationApplication.scala
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceImpl.scala
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/actor/AuthenticationState.scala
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/readside/AuthenticationDatabase.scala
  product_code/authentication_service/impl/src/test/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceSpec.scala
  product_code/certificate_service/CHANGELOG.md
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateServiceImpl.scala
  product_code/configuration_service/CHANGELOG.md
  product_code/configuration_service/impl/src/main/scala/de/upb/cs/uc4/configuration/impl/ConfigurationServiceImpl.scala
  product_code/course_service/CHANGELOG.md
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
  product_code/matriculation_service/CHANGELOG.md
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/Hashing.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/JsonUtility.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/UC4Service.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/ErrorType.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4Exception.scala
  product_code/shared/client/src/test/scala/de/upb/cs/uc4/shared/client/UC4ServiceSpec.scala
  product_code/shared/server/src/main/scala/de/upb/cs/uc4/shared/server/kafka/KafkaEncryptionUtility.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserServiceSpec.scala
Labels: Lagom, enhancement

#356 Feature/matriculation proposals
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateServiceImpl.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/HyperledgerDefaultActorFactory.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/commands/HyperledgerProposalCommand.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/commands/SubmitProposal.scala
  product_code/matriculation_service/CHANGELOG.md
  product_code/matriculation_service/api/src/main/scala/de/upb/cs/uc4/matriculation/api/MatriculationService.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/actor/MatriculationBehaviour.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/commands/AddEntriesToMatriculationData.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/commands/AddMatriculationData.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/commands/GetProposalForAddEntriesToMatriculationData.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/commands/GetProposalForAddMatriculationData.scala
  product_code/matriculation_service/impl/src/test/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceSpec.scala
  product_code/project/Version.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/SignedTransactionProposal.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/TransactionProposal.scala
Labels: Lagom

#361 Delete certificate user
  product_code/certificate_service/CHANGELOG.md
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateApplication.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateSerializerRegistry.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/actor/CertificateState.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/commands/DeleteCertificateUser.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/events/OnCertificateUserDelete.scala
  product_code/certificate_service/impl/src/test/scala/de/upb/cs/uc4/certificate/impl/CertificateServiceSpec.scala
  product_code/certificate_service/impl/src/test/scala/de/upb/cs/uc4/certificate/impl/CertificateStateSpec.scala
Labels: Lagom, bug

#364 Make adjustments to support new HL-API v0.11.5
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/commands/SubmitProposal.scala
  product_code/matriculation_service/impl/src/test/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceSpec.scala
  product_code/project/Version.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/SignedTransactionProposal.scala
Labels: Lagom

#366 Change toPublic to be additive
  product_code/user_service/CHANGELOG.md
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Admin.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Lecturer.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Student.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/User.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserSpec.scala
Labels: Lagom, refactor

#367 Fix Json Registry
  product_code/authentication_service/CHANGELOG.md
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceImpl.scala
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/actor/AuthenticationState.scala
  product_code/authentication_service/impl/src/test/scala/de/upb/cs/uc4/authentication/impl/AuthenticationStateSpec.scala
  product_code/certificate_service/CHANGELOG.md
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateSerializerRegistry.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateServiceImpl.scala
  product_code/configuration_service/CHANGELOG.md
  product_code/course_service/CHANGELOG.md
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/actor/CourseState.scala
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseStateSpec.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/HyperledgerDefaultActorFactory.scala
  product_code/matriculation_service/CHANGELOG.md
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
  product_code/project/Version.scala
  product_code/shared/server/src/main/scala/de/upb/cs/uc4/shared/server/messages/Confirmation.scala
  product_code/shared/server/src/main/scala/de/upb/cs/uc4/shared/server/messages/Rejected.scala
  product_code/shared/server/src/main/scala/de/upb/cs/uc4/shared/server/messages/RejectedWithError.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/actor/UserState.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserStateSpec.scala
Labels: Lagom, bug

#369 Feature/fix serialization
  product_code/authentication_service/CHANGELOG.md
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationApplication.scala
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceImpl.scala
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/actor/AuthenticationState.scala
  product_code/authentication_service/impl/src/test/scala/de/upb/cs/uc4/authentication/impl/AuthenticationStateSpec.scala
  product_code/certificate_service/CHANGELOG.md
  product_code/certificate_service/impl/src/main/resources/application.conf
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateApplication.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateSerializerRegistry.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateServiceImpl.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/actor/CertificateState.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/actor/CertificateUser.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/commands/GetCertificateUser.scala
  product_code/certificate_service/impl/src/test/scala/de/upb/cs/uc4/certificate/impl/CertificateServiceSpec.scala
  product_code/certificate_service/impl/src/test/scala/de/upb/cs/uc4/certificate/impl/CertificateStateSpec.scala
  product_code/configuration_service/CHANGELOG.md
  product_code/configuration_service/impl/src/main/scala/de/upb/cs/uc4/configuration/impl/ConfigurationServiceImpl.scala
  product_code/course_service/CHANGELOG.md
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseApplication.scala
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/actor/CourseState.scala
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseServiceSpec.scala
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseStateSpec.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/HyperledgerDefaultActorFactory.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/commands/HyperledgerCommands.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/commands/SubmitProposal.scala
  product_code/matriculation_service/CHANGELOG.md
  product_code/matriculation_service/impl/src/main/resources/application.conf
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/actor/MatriculationBehaviour.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/commands/GetMatriculationData.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/commands/GetProposalForAddEntriesToMatriculationData.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/commands/GetProposalForAddMatriculationData.scala
  product_code/matriculation_service/impl/src/test/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceSpec.scala
  product_code/project/plugins.sbt
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/SignedTransactionProposal.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/UC4Service.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4CriticalException.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4Error.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4Exception.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4ExceptionSerializable.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4ExceptionSerializer.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4NonCriticalException.scala
  product_code/shared/server/src/main/scala/de/upb/cs/uc4/shared/server/messages/Accepted.scala
  product_code/shared/server/src/main/scala/de/upb/cs/uc4/shared/server/messages/Confirmation.scala
  product_code/shared/server/src/main/scala/de/upb/cs/uc4/shared/server/messages/Rejected.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/ImageUploadRouter.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserApplication.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/actor/UserState.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserServiceSpec.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserStateSpec.scala
Labels: Lagom, bug

#372 Feature/validation messages
  product_code/authentication_service/api/src/main/scala/de/upb/cs/uc4/authentication/model/AuthenticationUser.scala
  product_code/certificate_service/api/src/main/scala/de/upb/cs/uc4/certificate/model/EncryptedPrivateKey.scala
  product_code/certificate_service/api/src/main/scala/de/upb/cs/uc4/certificate/model/PostMessageCSR.scala
  product_code/configuration_service/CHANGELOG.md
  product_code/configuration_service/api/src/main/scala/de/upb/cs/uc4/configuration/model/ValidationConfiguration.scala
  product_code/course_service/api/src/main/scala/de/upb/cs/uc4/course/model/Course.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/configuration/ErrorMessageCollection.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/Address.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Lecturer.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/User.scala
Labels: Lagom

#376 Feature/configurable_timeouts
  product_code/authentication_service/CHANGELOG.md
  product_code/authentication_service/impl/src/main/resources/application.conf
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationApplication.scala
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceImpl.scala
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/readside/AuthenticationDatabase.scala
  product_code/certificate_service/CHANGELOG.md
  product_code/certificate_service/impl/src/main/resources/application.conf
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateApplication.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateServiceImpl.scala
  product_code/configuration_service/CHANGELOG.md
  product_code/configuration_service/impl/src/main/resources/application.conf
  product_code/configuration_service/impl/src/main/scala/de/upb/cs/uc4/configuration/impl/ConfigurationServiceImpl.scala
  product_code/course_service/CHANGELOG.md
  product_code/course_service/impl/src/main/resources/application.conf
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
  product_code/matriculation_service/CHANGELOG.md
  product_code/matriculation_service/impl/src/main/resources/application.conf
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/impl/src/main/resources/application.conf
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserApplication.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/readside/UserDatabase.scala
Labels: Lagom, enhancement

#377 Add backwards compatability by providing old endpoints functionality
  product_code/matriculation_service/CHANGELOG.md
  product_code/matriculation_service/api/src/main/scala/de/upb/cs/uc4/matriculation/api/MatriculationService.scala
  product_code/matriculation_service/api/src/main/scala/de/upb/cs/uc4/matriculation/model/PutMessageMatriculation.scala
  product_code/matriculation_service/api/src/main/scala/de/upb/cs/uc4/matriculation/model/SubjectMatriculation.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/actor/MatriculationBehaviour.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/commands/AddEntriesToMatriculationData.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/commands/AddMatriculationData.scala
  product_code/matriculation_service/impl/src/test/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceSpec.scala
  product_code/project/Version.scala
Labels: Lagom

#373 Feature/exam reg service
  product_code/build.sbt
  product_code/certificate_service/impl/src/main/resources/hyperledger_assets/connection_profile_kubernetes_local.yaml
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateApplication.scala
  product_code/configuration_service/impl/src/main/scala/de/upb/cs/uc4/configuration/impl/ConfigurationServiceImpl.scala
  product_code/course_service/CHANGELOG.md
  product_code/course_service/api/src/main/scala/de/upb/cs/uc4/course/api/CourseService.scala
  product_code/course_service/api/src/main/scala/de/upb/cs/uc4/course/model/Course.scala
  product_code/course_service/api/src/test/scala/de/upb/cs/uc4/course/CourseServiceStub.scala
  product_code/course_service/api/src/test/scala/de/upb/cs/uc4/course/CourseSpec.scala
  product_code/course_service/api/src/test/scala/de/upb/cs/uc4/course/DefaultTestCourses.scala
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseApplication.scala
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseServiceSpec.scala
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseStateSpec.scala
  product_code/examreg_service/CHANGELOG.md
  product_code/examreg_service/api/src/main/scala/de/upb/cs/uc4/examreg/api/ExamregService.scala
  product_code/examreg_service/api/src/main/scala/de/upb/cs/uc4/examreg/model/ExaminationRegulation.scala
  product_code/examreg_service/api/src/main/scala/de/upb/cs/uc4/examreg/model/Module.scala
  product_code/examreg_service/api/src/test/scala/de/upb/cs/uc4/examreg/DefaultTestExamRegs.scala
  product_code/examreg_service/api/src/test/scala/de/upb/cs/uc4/examreg/ExamregServiceStub.scala
  product_code/examreg_service/impl/src/main/resources/application.conf
  product_code/examreg_service/impl/src/main/resources/hyperledger_assets/connection_profile_kubernetes_local.yaml
  product_code/examreg_service/impl/src/main/resources/hyperledger_assets/wallet/cli.id
  product_code/examreg_service/impl/src/main/resources/logback.xml
  product_code/examreg_service/impl/src/main/resources/prod-application.conf
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/ExamregApplication.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/ExamregLoader.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/ExamregSerializerRegistry.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/ExamregServiceImpl.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/actor/ExamregDatabaseBehaviour.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/actor/ExamregHyperledgerBehaviour.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/actor/ExamregState.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/commands/CreateExamregDatabase.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/commands/CreateExamregHyperledger.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/commands/ExamregCommand.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/commands/ExamregCommandSerializable.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/commands/GetExamreg.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/events/ExamregEvent.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/events/OnExamregCreate.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/readside/ExamregDatabase.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/readside/ExamregEventProcessor.scala
  product_code/examreg_service/impl/src/test/scala/de/upb/cs/uc4/examreg/impl/ExamregServiceSpec.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/HyperledgerAdminParts.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/HyperledgerDefaultParts.scala
  product_code/matriculation_service/impl/src/main/resources/hyperledger_assets/connection_profile_kubernetes_local.yaml
  product_code/matriculation_service/impl/src/test/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceSpec.scala
  product_code/project/Version.scala
Labels: Lagom

#378 Bugfix/examreg queries
  product_code/course_service/CHANGELOG.md
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
  product_code/examreg_service/CHANGELOG.md
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/ExamregApplication.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/ExamregServiceImpl.scala
  product_code/examreg_service/impl/src/test/scala/de/upb/cs/uc4/examreg/impl/ExamregServiceSpec.scala
  product_code/project/Version.scala
Labels: Lagom

#379 Feature/examreg additional endpoints
  product_code/build.sbt
  product_code/configuration_service/api/src/main/scala/de/upb/cs/uc4/configuration/model/ValidationConfiguration.scala
  product_code/course_service/api/src/main/scala/de/upb/cs/uc4/course/model/Course.scala
  product_code/examreg_service/CHANGELOG.md
  product_code/examreg_service/api/src/main/scala/de/upb/cs/uc4/examreg/api/ExamregService.scala
  product_code/examreg_service/api/src/main/scala/de/upb/cs/uc4/examreg/model/ExaminationRegulation.scala
  product_code/examreg_service/api/src/main/scala/de/upb/cs/uc4/examreg/model/Module.scala
  product_code/examreg_service/api/src/test/scala/de/upb/cs/uc4/examreg/DefaultTestExamRegs.scala
  product_code/examreg_service/api/src/test/scala/de/upb/cs/uc4/examreg/ExamregServiceStub.scala
  product_code/examreg_service/api/src/test/scala/de/upb/cs/uc4/examreg/ExamregSpec.scala
  product_code/examreg_service/impl/src/main/resources/application.conf
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/ExamregSerializerRegistry.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/ExamregServiceImpl.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/actor/ExamregHyperledgerBehaviour.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/actor/ExamregState.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/commands/CloseExamregDatabase.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/commands/CloseExamregHyperledger.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/events/OnExamregClose.scala
  product_code/examreg_service/impl/src/test/scala/de/upb/cs/uc4/examreg/impl/ExamregServiceSpec.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/configuration/ErrorMessageCollection.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/configuration/RegexCollection.scala
Labels: Lagom, enhancement

#381 Feature/already deleted error
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/ExamregServiceImpl.scala
  product_code/examreg_service/impl/src/test/scala/de/upb/cs/uc4/examreg/impl/ExamregServiceSpec.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/ErrorType.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4Exception.scala
Labels: Lagom

#359 Add govId to PostMessages
  product_code/course_service/CHANGELOG.md
  product_code/matriculation_service/CHANGELOG.md
  product_code/project/Version.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/api/UserService.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageAdmin.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageLecturer.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageStudent.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageUser.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Admin.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Lecturer.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Student.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/User.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/DefaultTestUsers.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/PostMessageUserSpec.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserServiceStub.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserSpec.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/actor/UserState.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/commands/CreateUser.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/events/OnUserCreate.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/readside/UserDatabase.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserServiceSpec.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserStateSpec.scala
Labels: Lagom

#374 Refactor/post message user
  product_code/project/Version.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/api/UserService.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/PostMessageUser.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageAdmin.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageLecturer.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageStudent.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageUser.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Student.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/User.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/PostMessageUserSpec.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserServiceStub.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserSpec.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserServiceSpec.scala
Labels: Lagom, refactor

#375 Feature/user deletion
  product_code/authentication_service/CHANGELOG.md
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationApplication.scala
  product_code/authentication_service/impl/src/test/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceSpec.scala
  product_code/certificate_service/CHANGELOG.md
  product_code/certificate_service/api/src/main/scala/de/upb/cs/uc4/certificate/api/CertificateService.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateApplication.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateSerializerRegistry.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/actor/CertificateState.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/commands/DeleteCertificateUser.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/commands/ForceDeleteCertificateUser.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/commands/SoftDeleteCertificateUser.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/events/OnCertificateUserDelete.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/events/OnCertificateUserForceDelete.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/events/OnCertificateUserSoftDelete.scala
  product_code/certificate_service/impl/src/test/scala/de/upb/cs/uc4/certificate/impl/CertificateServiceSpec.scala
  product_code/certificate_service/impl/src/test/scala/de/upb/cs/uc4/certificate/impl/CertificateStateSpec.scala
  product_code/project/Version.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/api/UserService.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/JsonUserData.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Admin.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Lecturer.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Student.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/User.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/DefaultTestUsers.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserServiceStub.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserSpec.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserSerializerRegistry.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/actor/UserState.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/commands/ForceDeleteUser.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/commands/SoftDeleteUser.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/events/OnUserDelete.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/events/OnUserForceDelete.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/events/OnUserSoftDelete.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/readside/UserDatabase.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/readside/UserEventProcessor.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserServiceSpec.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserStateSpec.scala
Labels: Lagom

#392 Make course list public
  product_code/course_service/CHANGELOG.md
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseServiceSpec.scala
Labels: Lagom
