Repository upb-uc4/lagom-core, pull requests merged in 2020-09, with the labels that each got.

#248 Feature/course test cleanup
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseServiceSpec.scala
Labels: Lagom, refactor

#237 Feature/user endpoints merge
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/CustomError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/CustomException.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/message_serialization/CustomMessageSerializer.scala
  product_code/shared/client/src/test/scala/de/upb/cs/uc4/shared/client/UtilsSpec.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/api/UserService.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageAdmin.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageLecturer.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageStudent.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageUser.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Student.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/PostMessageUserSpec.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserServiceStub.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/actor/UserState.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserServiceSpec.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserStateSpec.scala
Labels: Lagom

#253 Adapt CourseServiceSpec to include the correct cleanup
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseServiceSpec.scala
Labels: Lagom

#257 Fix minor errors regarding error types
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/CustomException.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/ErrorType.scala
Labels: Lagom

#256 Add check if lecturer of a course does exist
  product_code/build.sbt
  product_code/course_service/CHANGELOG.md
  product_code/course_service/api/src/main/scala/de/upb/cs/uc4/course/api/CourseService.scala
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseApplication.scala
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseServiceSpec.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserServiceStub.scala
Labels: Lagom, bug

#265 Release/v0.8.0
  .github/workflows/lagom_deployment.yaml
  deployment/deploy_on_cluster.sh
  deployment/services/matriculation-storage.yaml
  deployment/services/matriculation.yaml
  product_code/authentication_service/CHANGELOG.md
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceImpl.scala
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/actor/AuthenticationState.scala
  product_code/build.sbt
  product_code/course_service/CHANGELOG.md
  product_code/course_service/api/src/main/scala/de/upb/cs/uc4/course/api/CourseService.scala
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseApplication.scala
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/actor/CourseState.scala
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseServiceSpec.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/HyperledgerActorFactory.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/HyperledgerUtils.scala
  product_code/matriculation_service/CHANGELOG.md
  product_code/matriculation_service/impl/src/main/resources/prod-application.conf
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
  product_code/matriculation_service/impl/src/test/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceSpec.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/CustomError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/CustomException.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/DetailedError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/ErrorType.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/GenericError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/InformativeError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/TransactionError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/message_serialization/CustomMessageSerializer.scala
  product_code/shared/client/src/test/scala/de/upb/cs/uc4/shared/client/UtilsSpec.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/api/UserService.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageAdmin.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageLecturer.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageStudent.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageUser.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Student.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/PostMessageUserSpec.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserServiceStub.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/actor/UserState.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserServiceSpec.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserStateSpec.scala
Labels: Lagom

#273 Feature/application config fix
  product_code/authentication_service/CHANGELOG.md
  product_code/authentication_service/impl/src/main/resources/prod-application.conf
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationApplication.scala
  product_code/course_service/CHANGELOG.md
  product_code/course_service/impl/src/main/resources/prod-application.conf
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseApplication.scala
  product_code/matriculation_service/CHANGELOG.md
  product_code/matriculation_service/impl/src/main/resources/prod-application.conf
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationApplication.scala
  product_code/shared/server/src/main/scala/de/upb/cs/uc4/shared/server/UC4Application.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/impl/src/main/resources/prod-application.conf
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserApplication.scala
Labels: Lagom

#281 Bugfix/user service
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/actor/UserState.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserStateSpec.scala
Labels: Lagom

#283 Add Gzip support in Options Header
  product_code/authentication_service/CHANGELOG.md
  product_code/build.sbt
  product_code/course_service/CHANGELOG.md
  product_code/matriculation_service/CHANGELOG.md
  product_code/shared/server/src/main/scala/de/upb/cs/uc4/shared/server/ServiceCallFactory.scala
  product_code/user_service/CHANGELOG.md
Labels: Lagom

#290 Add error for refresh token missing
  product_code/authentication_service/CHANGELOG.md
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceImpl.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/CustomException.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/ErrorType.scala
  product_code/shared/server/src/main/scala/de/upb/cs/uc4/shared/server/ServiceCallFactory.scala
Labels: Lagom

#289 CourseService: Move validation from State to Impl, add NotFound to validation
  product_code/course_service/CHANGELOG.md
  product_code/course_service/api/src/main/scala/de/upb/cs/uc4/course/model/Course.scala
  product_code/course_service/api/src/test/scala/de/upb/cs/uc4/course/CourseSpec.scala
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/actor/CourseState.scala
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseServiceSpec.scala
  product_test/test_documentation/validation/course-management.md
Labels: Lagom

#287 Bugfix/user service validation
  product_code/user_service/CHANGELOG.md
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserServiceSpec.scala
Labels: Lagom

#298 Separate build.sbt in multiple files
  product_code/build.sbt
  product_code/project/Dependencies.scala
  product_code/project/Settings.scala
  product_code/project/Version.scala
Labels: Lagom, refactor

#296 Refactor/authentication tests
  product_code/authentication_service/CHANGELOG.md
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceImpl.scala
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/readside/AuthenticationDatabase.scala
  product_code/authentication_service/impl/src/test/resources/application.conf
  product_code/authentication_service/impl/src/test/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceSpec.scala
  product_code/build.sbt
  product_code/matriculation_service/impl/src/test/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceSpec.scala
  product_code/project/Version.scala
Labels: Lagom, refactor

#299 Feature/image browsing
  product_code/project/Dependencies.scala
  product_code/project/Version.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/CustomError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/CustomException.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/ErrorType.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/api/UserService.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Admin.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Lecturer.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Student.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/User.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/DefaultTestUsers.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserServiceStub.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserSpec.scala
  product_code/user_service/impl/src/main/resources/application.conf
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/ImageUploadRouter.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserApplication.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/actor/UserState.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/commands/SetImage.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/events/OnImageSet.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/readside/UserDatabase.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/readside/UserEventProcessor.scala
  product_code/user_service/impl/src/test/resources/Example.png
  product_code/user_service/impl/src/test/resources/Example.svg
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserServiceSpec.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserStateSpec.scala
Labels: Lagom, enhancement

#303 Added Default Profile Picture
  product_code/project/Version.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/impl/src/main/resources/DefaultProfile.png
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/ImageUploadRouter.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserServiceSpec.scala
Labels: Lagom, enhancement

#305 bugfix/change_pw_creates_account
  product_code/authentication_service/impl/src/test/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceSpec.scala
Labels: Lagom

#308 Add better Internal Server Error
  product_code/.sbtopts
  product_code/authentication_service/impl/src/main/resources/logback.xml
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceImpl.scala
  product_code/authentication_service/impl/src/test/resources/logback-test.xml
  product_code/authentication_service/impl/src/test/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceSpec.scala
  product_code/course_service/impl/src/main/resources/logback.xml
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
  product_code/course_service/impl/src/test/resources/logback-test.xml
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseServiceSpec.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/HyperledgerActorFactory.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/HyperledgerUtils.scala
  product_code/matriculation_service/impl/src/main/resources/logback.xml
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/actor/MatriculationBehaviour.scala
  product_code/matriculation_service/impl/src/test/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceSpec.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/UC4Service.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/Utils.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/CustomException.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/DetailedError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/GenericError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/InformativeError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/TransactionError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4Error.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4Exception.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4ExceptionSerializer.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/message_serialization/CustomMessageSerializer.scala
  product_code/shared/client/src/test/resources/logback.xml
  product_code/shared/server/src/main/scala/de/upb/cs/uc4/shared/server/ServiceCallFactory.scala
  product_code/shared/server/src/main/scala/de/upb/cs/uc4/shared/server/messages/RejectedWithError.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageUser.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Student.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserServiceStub.scala
  product_code/user_service/impl/src/main/resources/logback.xml
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/ImageUploadRouter.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/test/resources/logback.xml
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserServiceSpec.scala
Labels: Lagom, bug, enhancement
