Repository upb-uc4/lagom-core, pull requests merged in 2020-10, with the labels that each got.

#311 Improve UserServiceStub
  product_code/build.sbt
  product_code/course_service/api/src/test/scala/de/upb/cs/uc4/course/CourseServiceStub.scala
  product_code/course_service/api/src/test/scala/de/upb/cs/uc4/course/DefaultTestCourses.scala
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseServiceSpec.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserServiceStub.scala
Labels: Lagom

#309 Feature/validation timeout
  product_code/authentication_service/CHANGELOG.md
  product_code/authentication_service/api/src/main/scala/de/upb/cs/uc4/authentication/model/AuthenticationUser.scala
  product_code/authentication_service/api/src/test/scala/de/upb/cs/uc4/authentication/AuthenticationUserSpec.scala
  product_code/authentication_service/impl/src/main/resources/application.conf
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceImpl.scala
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/actor/AuthenticationState.scala
  product_code/course_service/CHANGELOG.md
  product_code/course_service/api/src/main/scala/de/upb/cs/uc4/course/model/Course.scala
  product_code/course_service/api/src/test/scala/de/upb/cs/uc4/course/CourseSpec.scala
  product_code/course_service/impl/src/main/resources/application.conf
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
  product_code/matriculation_service/CHANGELOG.md
  product_code/matriculation_service/api/src/main/scala/de/upb/cs/uc4/matriculation/model/PutMessageMatriculation.scala
  product_code/matriculation_service/api/src/main/scala/de/upb/cs/uc4/matriculation/model/SubjectMatriculation.scala
  product_code/matriculation_service/api/src/test/scala/de/upb/cs/uc4/matriculation/PutMessageMatriculationSpec.scala
  product_code/matriculation_service/api/src/test/scala/de/upb/cs/uc4/matriculation/SubjectMatriculationSpec.scala
  product_code/matriculation_service/impl/src/main/resources/application.conf
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/ErrorType.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4Error.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4Exception.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/message_serialization/CustomMessageSerializer.scala
  product_code/shared/server/src/main/scala/de/upb/cs/uc4/shared/server/ServiceCallFactory.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/Address.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageAdmin.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageLecturer.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageStudent.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageUser.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Lecturer.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Student.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/User.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/PostMessageUserSpec.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserSpec.scala
  product_code/user_service/impl/src/main/resources/application.conf
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
Labels: Lagom

#318 Feature/sbt checks
  .github/workflows/lagom_deployment.yaml
  .github/workflows/lagom_manual_dependency.yaml
  .github/workflows/lagom_manual_deployment.yaml
  product_code/build.sbt
  product_code/project/Commands.scala
  product_code/project/Settings.scala
Labels: Lagom

#329 Clean up certificate service
  product_code/certificate_service/CHANGELOG.md
  product_code/certificate_service/api/src/main/scala/de/upb/cs/uc4/certificate/api/CertificateService.scala
  product_code/certificate_service/api/src/main/scala/de/upb/cs/uc4/certificate/model/EncryptedPrivateKey.scala
  product_code/certificate_service/api/src/main/scala/de/upb/cs/uc4/certificate/model/PostMessageCSR.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateServiceImpl.scala
  product_code/certificate_service/impl/src/test/scala/de/upb/cs/uc4/certificate/impl/CertificateServiceSpec.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/HyperledgerDefaultActorFactory.scala
Labels: Lagom, bug

#328 Add pseudonymisation in MatriculationService
  product_code/build.sbt
  product_code/certificate_service/api/src/test/scala/de/upb/cs/uc4/certificate/CertificateServiceStub.scala
  product_code/certificate_service/api/src/test/scala/de/upb/cs/uc4/certificate/CertificateUserEntry.scala
  product_code/matriculation_service/CHANGELOG.md
  product_code/matriculation_service/api/src/main/scala/de/upb/cs/uc4/matriculation/model/ImmatriculationData.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationApplication.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
  product_code/matriculation_service/impl/src/test/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceSpec.scala
Labels: Lagom

#333 Fix wrong response code
  product_code/build.sbt
  product_code/certificate_service/CHANGELOG.md
  product_code/certificate_service/api/src/main/scala/de/upb/cs/uc4/certificate/api/CertificateService.scala
  product_code/certificate_service/api/src/test/scala/de/upb/cs/uc4/certificate/CertificateServiceStub.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateServiceImpl.scala
  product_code/certificate_service/impl/src/test/scala/de/upb/cs/uc4/certificate/impl/CertificateServiceSpec.scala
  product_code/project/Dependencies.scala
  product_code/project/Version.scala
Labels: Lagom

#334 Feature/error handling
  product_code/authentication_service/CHANGELOG.md
  product_code/authentication_service/impl/src/main/resources/application.conf
  product_code/authentication_service/impl/src/main/resources/logback.xml
  product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceImpl.scala
  product_code/authentication_service/impl/src/test/resources/logback-test.xml
  product_code/authentication_service/impl/src/test/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceSpec.scala
  product_code/certificate_service/CHANGELOG.md
  product_code/certificate_service/api/src/test/scala/de/upb/cs/uc4/certificate/CertificateServiceStub.scala
  product_code/certificate_service/impl/src/main/resources/application.conf
  product_code/certificate_service/impl/src/main/resources/logback.xml
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateApplication.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateServiceImpl.scala
  product_code/certificate_service/impl/src/test/resources/logback.xml
  product_code/course_service/CHANGELOG.md
  product_code/course_service/api/src/test/scala/de/upb/cs/uc4/course/CourseServiceStub.scala
  product_code/course_service/impl/src/main/resources/application.conf
  product_code/course_service/impl/src/main/resources/logback.xml
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
  product_code/course_service/impl/src/test/resources/logback-test.xml
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/HyperledgerDefaultActorFactory.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/HyperledgerUtils.scala
  product_code/matriculation_service/CHANGELOG.md
  product_code/matriculation_service/impl/src/main/resources/application.conf
  product_code/matriculation_service/impl/src/main/resources/logback.xml
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/actor/MatriculationBehaviour.scala
  product_code/matriculation_service/impl/src/test/resources/logback-test.xml
  product_code/matriculation_service/impl/src/test/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceSpec.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/Utils.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/DetailedError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/InformativeError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/SimpleError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/TransactionError.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4CriticalException.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4Error.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4Exception.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4ExceptionSerializer.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4NonCriticalException.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/message_serialization/CustomMessageSerializer.scala
  product_code/shared/server/src/main/scala/de/upb/cs/uc4/shared/server/ServiceCallFactory.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/post/PostMessageUser.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Student.scala
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserServiceStub.scala
  product_code/user_service/impl/src/main/resources/application.conf
  product_code/user_service/impl/src/main/resources/logback.xml
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/ImageUploadRouter.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/actor/UserState.scala
  product_code/user_service/impl/src/test/resources/logback-test.xml
  product_code/user_service/impl/src/test/resources/logback.xml
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserStateSpec.scala
Labels: Lagom

#337 Feature/configuration service
  product_code/authentication_service/CHANGELOG.md
  product_code/authentication_service/api/src/main/scala/de/upb/cs/uc4/authentication/model/AuthenticationUser.scala
  product_code/build.sbt
  product_code/certificate_service/api/src/main/scala/de/upb/cs/uc4/certificate/model/EncryptedPrivateKey.scala
  product_code/configuration_service/CHANGELOG.md
  product_code/configuration_service/api/src/main/scala/de/upb/cs/uc4/configuration/api/ConfigurationService.scala
  product_code/configuration_service/api/src/main/scala/de/upb/cs/uc4/configuration/model/Configuration.scala
  product_code/configuration_service/api/src/main/scala/de/upb/cs/uc4/configuration/model/HyperledgerVersions.scala
  product_code/configuration_service/api/src/main/scala/de/upb/cs/uc4/configuration/model/JsonSemester.scala
  product_code/configuration_service/api/src/main/scala/de/upb/cs/uc4/configuration/model/ValidationConfiguration.scala
  product_code/configuration_service/impl/src/main/resources/application.conf
  product_code/configuration_service/impl/src/main/resources/logback.xml
  product_code/configuration_service/impl/src/main/resources/prod-application.conf
  product_code/configuration_service/impl/src/main/scala/de/upb/cs/uc4/configuration/impl/ConfigurationApplication.scala
  product_code/configuration_service/impl/src/main/scala/de/upb/cs/uc4/configuration/impl/ConfigurationLoader.scala
  product_code/configuration_service/impl/src/main/scala/de/upb/cs/uc4/configuration/impl/ConfigurationServiceImpl.scala
  product_code/configuration_service/impl/src/test/scala/de/upb/cs/uc4/configuration/impl/ConfigurationServiceSpec.scala
  product_code/course_service/CHANGELOG.md
  product_code/course_service/api/src/main/scala/de/upb/cs/uc4/course/model/Course.scala
  product_code/course_service/api/src/test/scala/de/upb/cs/uc4/course/DefaultTestCourses.scala
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseStateSpec.scala
  product_code/matriculation_service/CHANGELOG.md
  product_code/matriculation_service/api/src/main/scala/de/upb/cs/uc4/matriculation/model/SubjectMatriculation.scala
  product_code/project/Version.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/Utils.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/configuration/ConfigurationCollection.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/configuration/CourseLanguage.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/configuration/CourseType.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/configuration/RegexCollection.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/ErrorType.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4Exception.scala
  product_code/shared/client/src/test/scala/de/upb/cs/uc4/shared/client/UtilsSpec.scala
  product_code/shared/server/src/test/scala/de/upb/cs/uc4/shared/server/ServiceCallFactorySpec.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/Address.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Lecturer.scala
  product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/User.scala
Labels: Lagom

#339 Feature/robust hl api
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateApplication.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/HyperledgerDefaultActorFactory.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/commands/HyperledgerCommand.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/commands/HyperledgerCommands.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/commands/HyperledgerReadCommand.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/commands/HyperledgerWriteCommand.scala
  product_code/hyperledger_component/src/main/scala/de/upb/cs/uc4/hyperledger/commands/Shutdown.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/commands/AddEntriesToMatriculationData.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/commands/AddMatriculationData.scala
  product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/commands/GetMatriculationData.scala
  product_code/project/Version.scala
Labels: Lagom

#344 Feature/hl new mounts
  deployment/deploy_on_cluster.sh
  deployment/services/certificate-storage.yaml
  deployment/services/certificate.yaml
  deployment/services/matriculation-storage.yaml
  deployment/services/matriculation.yaml
  product_code/certificate_service/CHANGELOG.md
  product_code/certificate_service/impl/src/main/resources/prod-application.conf
  product_code/matriculation_service/CHANGELOG.md
  product_code/matriculation_service/impl/src/main/resources/prod-application.conf
Labels: Hyperledger, Lagom

#343 Add gzip threshold
  product_code/authentication_service/CHANGELOG.md
  product_code/authentication_service/impl/src/main/resources/application.conf
  product_code/authentication_service/impl/src/main/resources/prod-application.conf
  product_code/certificate_service/CHANGELOG.md
  product_code/certificate_service/impl/src/main/resources/application.conf
  product_code/certificate_service/impl/src/main/resources/prod-application.conf
  product_code/configuration_service/CHANGELOG.md
  product_code/configuration_service/impl/src/main/resources/application.conf
  product_code/configuration_service/impl/src/main/resources/prod-application.conf
  product_code/course_service/CHANGELOG.md
  product_code/course_service/impl/src/main/resources/application.conf
  product_code/course_service/impl/src/main/resources/prod-application.conf
  product_code/matriculation_service/CHANGELOG.md
  product_code/matriculation_service/impl/src/main/resources/application.conf
  product_code/matriculation_service/impl/src/main/resources/prod-application.conf
  product_code/user_service/CHANGELOG.md
  product_code/user_service/impl/src/main/resources/application.conf
  product_code/user_service/impl/src/main/resources/prod-application.conf
Labels: Lagom

#347 Adjust to new credentials system
  deployment/full_start.sh
  deployment/services/certificate.yaml
  deployment/services/matriculation.yaml
Labels: Hyperledger, Lagom

#346 Feature/validation improvement
  product_code/authentication_service/api/src/main/scala/de/upb/cs/uc4/authentication/model/AuthenticationUser.scala
  product_code/certificate_service/api/src/main/scala/de/upb/cs/uc4/certificate/model/PostMessageCSR.scala
  product_code/configuration_service/CHANGELOG.md
  product_code/configuration_service/api/src/main/scala/de/upb/cs/uc4/configuration/model/ValidationConfiguration.scala
  product_code/course_service/CHANGELOG.md
  product_code/course_service/api/src/main/scala/de/upb/cs/uc4/course/model/Course.scala
  product_code/course_service/api/src/test/scala/de/upb/cs/uc4/course/CourseSpec.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/configuration/RegexCollection.scala
Labels: Lagom
