Repository upb-uc4/lagom-core, pull requests merged in 2021-01, with the labels that each got.

#421 Add missing catches in UserService topics. Add more precise logs
  product_code/user_service/CHANGELOG.md
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
Labels: Lagom

#418 Feature/gdpr
  product_code/admission_service/api/src/test/scala/de/upb/cs/uc4/admission/AdmissionServiceStub.scala
  product_code/admission_service/impl/src/main/scala/de/upb/cs/uc4/admission/impl/AdmissionApplication.scala
  product_code/build.sbt
  product_code/certificate_service/api/src/test/scala/de/upb/cs/uc4/certificate/CertificateServiceStub.scala
  product_code/certificate_service/impl/src/main/scala/de/upb/cs/uc4/certificate/impl/CertificateApplication.scala
  product_code/docker-compose.yaml
  product_code/docker/postgres.conf
  product_code/matriculation_service/api/src/test/scala/de/upb/cs/uc4/matriculation/MatriculationServiceStub.scala
  product_code/matriculation_service/impl/src/main/resources/application.conf
  product_code/project/Dependencies.scala
  product_code/project/Version.scala
  product_code/report_service/CHANGELOG.md
  product_code/report_service/api/src/main/scala/de/upb/cs/uc4/report/api/ReportService.scala
  product_code/report_service/impl/src/main/resources/application.conf
  product_code/report_service/impl/src/main/resources/logback.xml
  product_code/report_service/impl/src/main/resources/prod-application.conf
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/ReportApplication.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/ReportLoader.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/ReportSerializerRegistry.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/ReportServiceImpl.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/actor/Report.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/actor/ReportBehaviour.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/actor/ReportState.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/actor/ReportStateEnum.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/actor/ReportWrapper.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/commands/DeleteReport.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/commands/GetReport.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/commands/PrepareReport.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/commands/ReportCommand.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/commands/ReportCommandSerializable.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/commands/SetReport.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/events/OnDeleteReport.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/events/OnPrepareReport.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/events/OnSetReport.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/events/ReportEvent.scala
  product_code/report_service/impl/src/test/resources/logback-test.xml
  product_code/report_service/impl/src/test/scala/de/upb/cs/uc4/report/impl/ReportServiceSpec.scala
  product_code/report_service/impl/src/test/scala/de/upb/cs/uc4/report/impl/ReportStateSpec.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/ErrorType.scala
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/exceptions/UC4Exception.scala
  product_code/user_service/CHANGELOG.md
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
Labels: Lagom

#426 Bugfix examreg caching
  product_code/examreg_service/CHANGELOG.md
  product_code/examreg_service/api/src/main/scala/de/upb/cs/uc4/examreg/model/ExaminationRegulationsWrapper.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/ExamregApplication.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/ExamregSerializerRegistry.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/actor/ExamregHyperledgerBehaviour.scala
  product_code/examreg_service/impl/src/main/scala/de/upb/cs/uc4/examreg/impl/commands/GetAllExamregsHyperledger.scala
Labels: Lagom

#428 Add profile pictures and thumnails to report
  product_code/report_service/api/src/main/scala/de/upb/cs/uc4/report/api/ReportService.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/ReportSerializerRegistry.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/ReportServiceImpl.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/actor/ReportState.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/actor/ReportWrapper.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/actor/TextReport.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/commands/SetReport.scala
  product_code/report_service/impl/src/main/scala/de/upb/cs/uc4/report/impl/events/OnSetReport.scala
  product_code/report_service/impl/src/test/scala/de/upb/cs/uc4/report/impl/ReportStateSpec.scala
  product_code/user_service/api/src/test/resources/DefaultThumbnail.jpg
  product_code/user_service/api/src/test/scala/de/upb/cs/uc4/user/UserServiceStub.scala
  product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
Labels: Lagom, enhancement

#437 Feature/test coverage
  product_code/authentication_service/impl/src/test/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceSpec.scala
  product_code/certificate_service/impl/src/test/scala/de/upb/cs/uc4/certificate/impl/CertificateServiceSpec.scala
  product_code/configuration_service/impl/src/test/scala/de/upb/cs/uc4/configuration/impl/ConfigurationServiceSpec.scala
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseServiceSpec.scala
  product_code/examreg_service/api/src/test/scala/de/upb/cs/uc4/examreg/ExamregServiceStub.scala
  product_code/examreg_service/impl/src/test/scala/de/upb/cs/uc4/examreg/impl/ExamregServiceSpec.scala
  product_code/matriculation_service/impl/src/test/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceSpec.scala
  product_code/user_service/impl/src/test/resources/Example_thumbnail.jpeg
  product_code/user_service/impl/src/test/scala/de/upb/cs/uc4/user/impl/UserServiceSpec.scala
Labels: Lagom

#443 Remove an unused message and refactor lecturerID error message
  product_code/course_service/CHANGELOG.md
  product_code/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/configuration/ErrorMessageCollection.scala
Labels: Lagom

#441 Fix ReadMe
  README.md
  documentation/dependency_tree.jpg
  product_code/.sbtopts
  product_code/ReadMe.md
  product_test/automatic_test/.gitkeep
  product_test/integration_test.yml
  product_test/manual_test/BasicDirtyManualTest.md
Labels: documentation

#439 Add examregName filter to getAllCourses
  product_code/course_service/CHANGELOG.md
  product_code/course_service/api/src/main/scala/de/upb/cs/uc4/course/api/CourseService.scala
  product_code/course_service/api/src/test/scala/de/upb/cs/uc4/course/CourseServiceStub.scala
  product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
  product_code/course_service/impl/src/test/scala/de/upb/cs/uc4/course/impl/CourseServiceSpec.scala
  product_code/project/Version.scala
Labels: Lagom
